// <auto-generated />
using System;
using Epets.App.Persistencia.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Epets.App.Persistencia.Migrations
{
    [DbContext(typeof(MfAppContext))]
    partial class MfAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Epets.App.Dominio.Entidades.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("DireccionEmpresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Direccion");

                    b.Property<int>("Nit")
                        .HasColumnType("int")
                        .HasColumnName("Nit");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdEmpresa");

                    b.ToTable("EmpresaDb");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.Historia", b =>
                {
                    b.Property<int>("IdHistoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaVisita")
                        .HasMaxLength(12)
                        .HasColumnType("datetime2")
                        .HasColumnName("DateTime");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Medicamento");

                    b.Property<string>("Recomendaciones")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Recomendaciones");

                    b.HasKey("IdHistoria");

                    b.ToTable("Historia");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("ColorOjos")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ColorOjos");

                    b.Property<string>("ColorPiel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ColorPiel");

                    b.Property<float>("Estatura")
                        .HasColumnType("real")
                        .HasColumnName("Estatura");

                    b.Property<int?>("IdHistoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdPropietario")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoAnimal")
                        .HasColumnType("int");

                    b.Property<string>("NombreMascota")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("NombreMascota");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Raza");

                    b.HasKey("IdMascota");

                    b.HasIndex("IdHistoria");

                    b.HasIndex("IdPropietario");

                    b.HasIndex("IdTipoAnimal");

                    b.ToTable("MascotaDb");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Cedula");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoAnimal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Nombre");

                    b.Property<int>("TarjetaProfesional")
                        .HasColumnType("int")
                        .HasColumnName("TarjetaProfesional");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdTipoAnimal");

                    b.ToTable("MedicoDb");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.Propietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Cedula");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Telefono");

                    b.HasKey("Id");

                    b.ToTable("PropietariosDb");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.SolicitudVisita", b =>
                {
                    b.Property<int>("IdSolicitudVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaVisita")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaVisita");

                    b.Property<int?>("IdMascota")
                        .HasColumnType("int");

                    b.Property<int?>("IdPropietario")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoAnimal")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitudVisita");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdPropietario");

                    b.HasIndex("IdTipoAnimal");

                    b.ToTable("SolicitudVisitaDb");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.TipoSigno", b =>
                {
                    b.Property<int>("IdTipoSigno")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("EstadoAnimo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("EstadoAnimo");

                    b.Property<int>("Frecuencia_Respiratoria")
                        .HasColumnType("int")
                        .HasColumnName("FrecuenciaRespiratoria");

                    b.Property<int>("Freuencia_Cardiaca")
                        .HasColumnType("int")
                        .HasColumnName("FrecuenciaCardiaca");

                    b.Property<int>("Peso")
                        .HasColumnType("int")
                        .HasColumnName("Peso");

                    b.Property<int>("Temperatura")
                        .HasColumnType("int")
                        .HasColumnName("Temperatura");

                    b.HasKey("IdTipoSigno");

                    b.ToTable("TipoSignoDb");
                });

            modelBuilder.Entity("Epets.App.Dominio.TipoAnimal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<string>("T_Animal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("T_Animal");

                    b.HasKey("IdAnimal");

                    b.ToTable("TipoAnimalDb");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.Mascota", b =>
                {
                    b.HasOne("Epets.App.Dominio.Entidades.Historia", "Historia")
                        .WithMany()
                        .HasForeignKey("IdHistoria");

                    b.HasOne("Epets.App.Dominio.Entidades.Propietario", "Propietario")
                        .WithMany()
                        .HasForeignKey("IdPropietario");

                    b.HasOne("Epets.App.Dominio.TipoAnimal", "TipoAnimal")
                        .WithMany()
                        .HasForeignKey("IdTipoAnimal");

                    b.Navigation("Historia");

                    b.Navigation("Propietario");

                    b.Navigation("TipoAnimal");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.Medico", b =>
                {
                    b.HasOne("Epets.App.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa");

                    b.HasOne("Epets.App.Dominio.TipoAnimal", "TipoAnimal")
                        .WithMany()
                        .HasForeignKey("IdTipoAnimal");

                    b.Navigation("Empresa");

                    b.Navigation("TipoAnimal");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.SolicitudVisita", b =>
                {
                    b.HasOne("Epets.App.Dominio.Entidades.Mascota", "Mascota")
                        .WithMany()
                        .HasForeignKey("IdMascota");

                    b.HasOne("Epets.App.Dominio.Entidades.Propietario", "Propietario")
                        .WithMany()
                        .HasForeignKey("IdPropietario");

                    b.HasOne("Epets.App.Dominio.TipoAnimal", "TipoAnimal")
                        .WithMany()
                        .HasForeignKey("IdTipoAnimal");

                    b.Navigation("Mascota");

                    b.Navigation("Propietario");

                    b.Navigation("TipoAnimal");
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.TipoSigno", b =>
                {
                    b.HasOne("Epets.App.Dominio.Entidades.Historia", null)
                        .WithMany("TipoSigno")
                        .HasForeignKey("IdTipoSigno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Epets.App.Dominio.Entidades.Historia", b =>
                {
                    b.Navigation("TipoSigno");
                });
#pragma warning restore 612, 618
        }
    }
}
